[package]
name = "boon-python"
version = "0.11.0"
rust-version.workspace = true
edition = "2024"
description = "Python bindings for the Boon Deadlock demo parser"
repository = "https://github.com/pnxenopoulos/boon"
license = "MIT"
publish = false

[lib]
name = "_boon"
crate-type = ["cdylib"]

[dependencies]
serde_json.workspace = true
boon_parser = { path = "../boon", package = "boon-deadlock" }
boon-proto = { workspace = true }
prost.workspace = true
pyo3 = { version = "0.27", features = ["extension-module", "multiple-pymethods"] }
pyo3-polars = "0.26"
polars = "0.53"

[lints]
workspace = true
