//! Generate the remaining static breakable lookup from misc.vdata.
//! Hero, ability, and modifier names are read from boon-data at runtime.

use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
};

const SEED: u32 = 0x31415926;

fn murmur_hash2(key: &[u8]) -> u32 {
    const M: u32 = 0x5BD1E995;
    const R: i32 = 24;

    let len = key.len();
    let mut h: u32 = SEED ^ (len as u32);
    let mut i = 0;

    while i + 4 <= len {
        let mut k = u32::from_le_bytes([key[i], key[i + 1], key[i + 2], key[i + 3]]);
        k = k.wrapping_mul(M);
        k ^= k >> R;
        k = k.wrapping_mul(M);
        h = h.wrapping_mul(M);
        h ^= k;
        i += 4;
    }

    let remaining = len - i;
    if remaining >= 3 {
        h ^= (key[i + 2] as u32) << 16;
    }
    if remaining >= 2 {
        h ^= (key[i + 1] as u32) << 8;
    }
    if remaining >= 1 {
        h ^= key[i] as u32;
        h = h.wrapping_mul(M);
    }

    h ^= h >> 13;
    h = h.wrapping_mul(M);
    h ^= h >> 15;
    h
}

/// Parse a KV3 `key = "value"` assignment line.
///
/// Return the unquoted value when `line` is the specified assignment. Return
/// `None` for a different key, an empty value, or a value that is not a string.
/// Remove surrounding whitespace from `line` before the call.
fn kv3_string_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim();
    let value = rest.strip_prefix('"')?.strip_suffix('"')?;
    (!value.is_empty()).then_some(value)
}

/// Extract top-level keys from a vdata file.
///
/// Matches lines like `\tkey_name = ` — one tab of indent followed by
/// a word-character key. Skips metadata keys (`generic_data_type`, `_include`).

/// Extract top-level object names whose direct `_class` matches `target_class`.
///
/// `misc.vdata` is a flat catalog: each entity template is a top-level object,
/// and its discriminator is a direct child two tabs deep. Restricting the class
/// check to that depth prevents a nested child class from classifying its parent.
fn extract_top_level_keys_by_class<'a>(content: &'a str, target_class: &str) -> Vec<&'a str> {
    let mut names = Vec::new();
    let mut current_name: Option<&str> = None;
    let mut current_matches = false;

    let flush = |name: &mut Option<&'a str>, matches: &mut bool, names: &mut Vec<&'a str>| {
        if *matches && let Some(name) = name.take() {
            names.push(name);
        }
        *name = None;
        *matches = false;
    };

    for line in content.lines() {
        if let Some(rest) = line.strip_prefix('\t')
            && !rest.starts_with('\t')
        {
            let key_end = rest
                .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                .unwrap_or(rest.len());
            let after = rest[key_end..].trim_start();
            if key_end > 0 && after.starts_with('=') {
                flush(&mut current_name, &mut current_matches, &mut names);
                let key = &rest[..key_end];
                if !["generic_data_type", "_include"].contains(&key) {
                    current_name = Some(key);
                }
                continue;
            }
        }

        if current_name.is_some()
            && line.starts_with("\t\t")
            && !line.starts_with("\t\t\t")
            && kv3_string_value(line.trim(), "_class") == Some(target_class)
        {
            current_matches = true;
        }
    }

    flush(&mut current_name, &mut current_matches, &mut names);
    names
}

fn hash_entries<'a>(names: &[&'a str]) -> Vec<(u32, &'a str)> {
    let mut entries: Vec<(u32, &str)> = names
        .iter()
        .map(|&name| (murmur_hash2(name.as_bytes()), name))
        .collect();
    entries.sort_by_key(|&(h, _)| h);
    entries
}

/// Generate a Rust source file with a hash → name lookup function and an
/// `all_*()` function returning all entries as a static slice.
fn write_hash_table(
    output_path: &Path,
    entries: &[(u32, &str)],
    source_file: &str,
    fn_name: &str,
    all_fn_name: &str,
    not_found: &str,
    today: &str,
) {
    let mut out = fs::File::create(output_path).expect("failed to create output file");

    writeln!(
        out,
        "//! Auto-generated by scripts/generate-name-tables from {source_file}"
    )
    .unwrap();
    writeln!(
        out,
        "//! Maps MurmurHash2(name, seed=0x31415926) \u{2192} name string."
    )
    .unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Last updated: {today}").unwrap();
    writeln!(out).unwrap();

    // Static slice for all_*()
    writeln!(out, "/// All known (hash, name) pairs sorted by hash.").unwrap();
    writeln!(out, "const ENTRIES: &[(u32, &str)] = &[").unwrap();
    for (hash, name) in entries {
        writeln!(out, "    ({hash}, \"{name}\"),").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Lookup function
    writeln!(out, "/// Look up a name by its MurmurHash2 ID.").unwrap();
    writeln!(out, "pub fn {fn_name}(id: u32) -> &'static str {{").unwrap();
    writeln!(out, "    match id {{").unwrap();
    for (hash, name) in entries {
        writeln!(out, "        {hash} => \"{name}\",").unwrap();
    }
    writeln!(out, "        _ => \"{not_found}\",").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // all_*() function
    writeln!(out, "/// Return all known (hash, name) pairs.").unwrap();
    writeln!(
        out,
        "pub fn {all_fn_name}() -> &'static [(u32, &'static str)] {{"
    )
    .unwrap();
    writeln!(out, "    ENTRIES").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Tests
    writeln!(out, "#[cfg(test)]").unwrap();
    writeln!(out, "mod tests {{").unwrap();
    writeln!(out, "    use super::*;").unwrap();
    writeln!(out).unwrap();

    if let Some(&(first_hash, first_name)) = entries.first() {
        writeln!(out, "    #[test]").unwrap();
        writeln!(out, "    fn known_first_entry() {{").unwrap();
        writeln!(
            out,
            "        assert_eq!({fn_name}({first_hash}), \"{first_name}\");"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }

    if entries.len() > 1 {
        let mid = entries.len() / 2;
        let (mid_hash, mid_name) = entries[mid];
        writeln!(out, "    #[test]").unwrap();
        writeln!(out, "    fn known_mid_entry() {{").unwrap();
        writeln!(
            out,
            "        assert_eq!({fn_name}({mid_hash}), \"{mid_name}\");"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn unknown_id_zero() {{").unwrap();
    writeln!(out, "        assert_eq!({fn_name}(0), \"{not_found}\");").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn unknown_id_max() {{").unwrap();
    writeln!(
        out,
        "        assert_eq!({fn_name}(u32::MAX), \"{not_found}\");"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn {all_fn_name}_not_empty() {{").unwrap();
    writeln!(out, "        assert!(!{all_fn_name}().is_empty());").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();

    eprintln!(
        "Wrote {} with {} entries",
        output_path.display(),
        entries.len()
    );
}

fn main() {
    let directory = std::env::var_os("BOON_VDATA_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let content = fs::read_to_string(directory.join("misc.vdata"))
        .expect("read misc.vdata from BOON_VDATA_DIR");
    let names = extract_top_level_keys_by_class(&content, "citadel_breakable_prop");
    write_hash_table(
        Path::new("crates/boon/src/breakables.rs"),
        &hash_entries(&names),
        "misc.vdata (`citadel_breakable_prop` entries)",
        "breakable_name",
        "all_breakables",
        "BREAKABLE_NOT_FOUND",
        &chrono_free_today(),
    );
}

fn chrono_free_today() -> String {
    // Use std::process::Command to get the date
    let output = std::process::Command::new("date")
        .arg("+%Y-%m-%d")
        .output()
        .expect("failed to run date command");
    String::from_utf8(output.stdout)
        .expect("invalid utf8 from date")
        .trim()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_only_direct_breakable_classes() {
        let content = concat!(
            "{\n",
            "\tgeneric_data_type = \"misc\"\n",
            "\tcitadel_breakable_prop_wooden_crate =\n",
            "\t{\n",
            "\t\t_class = \"citadel_breakable_prop\"\n",
            "\t}\n",
            "\tnon_breakable_parent =\n",
            "\t{\n",
            "\t\t_class = \"some_other_class\"\n",
            "\t\tchild =\n",
            "\t\t{\n",
            "\t\t\t_class = \"citadel_breakable_prop\"\n",
            "\t\t}\n",
            "\t}\n",
            "\tvehicle_car_01 =\n",
            "\t{\n",
            "\t\t_class = \"citadel_breakable_prop\"\n",
            "\t}\n",
            "}\n",
        );

        assert_eq!(
            extract_top_level_keys_by_class(content, "citadel_breakable_prop"),
            vec!["citadel_breakable_prop_wooden_crate", "vehicle_car_01"]
        );
    }
}
