//! Auto-generated by scripts/generate-name-tables from misc.vdata (`citadel_breakable_prop` entries)
//! Maps MurmurHash2(name, seed=0x31415926) → name string.
//!
//! Last updated: 2026-09-02

/// All known (hash, name) pairs sorted by hash.
const ENTRIES: &[(u32, &str)] = &[
    (50204002, "citadel_base_glass_horiz_01"),
    (479455394, "vehicle_car_05"),
    (818456624, "vehicle_large_truck_02"),
    (841549549, "citadel_breakable_prop_pumpkin04"),
    (844909675, "vehicle_car_01"),
    (985941184, "citadel_breakable_wooden_crate_03"),
    (1070887086, "citadel_breakable_prop_pumpkin01"),
    (1075096886, "citadel_breakable_wooden_crate_02"),
    (1153939632, "citadel_breakable_sake_barrel"),
    (1402417399, "citadel_breakable_prop_car"),
    (1413828045, "citadel_breakable_prop_pumpkin02"),
    (1467120186, "citadel_breakable_prop_xmaspresent01"),
    (1580763103, "citadel_breakable_prop_xmaspresent02"),
    (1702726906, "vehicle_large_truck_01"),
    (1786047166, "citadel_breakable_prop_base"),
    (2168482585, "citadel_breakable_lion_statue"),
    (2286845008, "citadel_breakable_prop_box_multi"),
    (2572218233, "citadel_breakable_prop_pumpkin03"),
    (2812656400, "vehicle_bike_flying"),
    (2902681599, "vehicle_mini_truck_03"),
    (3017498471, "citadel_breakable_prop_drop_gold"),
    (3040869273, "citadel_breakable_prop_vase"),
    (3087609631, "vehicle_ground_ship_03"),
    (3283028508, "vehicle_car_04"),
    (3457071437, "citadel_breakable_prop_drop_powerups"),
    (3508462982, "citadel_base_glass_vert_01"),
    (3719077267, "citadel_breakable_item_container"),
    (3986897915, "citadel_breakable_prop_wooden_crate"),
    (4027046556, "citadel_breakable_jar_01"),
    (4154240310, "citadel_breakable_prop_xmaspresent03"),
];

/// Look up a name by its MurmurHash2 ID.
pub fn breakable_name(id: u32) -> &'static str {
    match id {
        50204002 => "citadel_base_glass_horiz_01",
        479455394 => "vehicle_car_05",
        818456624 => "vehicle_large_truck_02",
        841549549 => "citadel_breakable_prop_pumpkin04",
        844909675 => "vehicle_car_01",
        985941184 => "citadel_breakable_wooden_crate_03",
        1070887086 => "citadel_breakable_prop_pumpkin01",
        1075096886 => "citadel_breakable_wooden_crate_02",
        1153939632 => "citadel_breakable_sake_barrel",
        1402417399 => "citadel_breakable_prop_car",
        1413828045 => "citadel_breakable_prop_pumpkin02",
        1467120186 => "citadel_breakable_prop_xmaspresent01",
        1580763103 => "citadel_breakable_prop_xmaspresent02",
        1702726906 => "vehicle_large_truck_01",
        1786047166 => "citadel_breakable_prop_base",
        2168482585 => "citadel_breakable_lion_statue",
        2286845008 => "citadel_breakable_prop_box_multi",
        2572218233 => "citadel_breakable_prop_pumpkin03",
        2812656400 => "vehicle_bike_flying",
        2902681599 => "vehicle_mini_truck_03",
        3017498471 => "citadel_breakable_prop_drop_gold",
        3040869273 => "citadel_breakable_prop_vase",
        3087609631 => "vehicle_ground_ship_03",
        3283028508 => "vehicle_car_04",
        3457071437 => "citadel_breakable_prop_drop_powerups",
        3508462982 => "citadel_base_glass_vert_01",
        3719077267 => "citadel_breakable_item_container",
        3986897915 => "citadel_breakable_prop_wooden_crate",
        4027046556 => "citadel_breakable_jar_01",
        4154240310 => "citadel_breakable_prop_xmaspresent03",
        _ => "BREAKABLE_NOT_FOUND",
    }
}

/// Return all known (hash, name) pairs.
pub fn all_breakables() -> &'static [(u32, &'static str)] {
    ENTRIES
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_first_entry() {
        assert_eq!(breakable_name(50204002), "citadel_base_glass_horiz_01");
    }

    #[test]
    fn known_mid_entry() {
        assert_eq!(breakable_name(2168482585), "citadel_breakable_lion_statue");
    }

    #[test]
    fn unknown_id_zero() {
        assert_eq!(breakable_name(0), "BREAKABLE_NOT_FOUND");
    }

    #[test]
    fn unknown_id_max() {
        assert_eq!(breakable_name(u32::MAX), "BREAKABLE_NOT_FOUND");
    }

    #[test]
    fn all_breakables_not_empty() {
        assert!(!all_breakables().is_empty());
    }
}
