//! Auto-generated by `scripts/generate-name-tables` from `heroes.vdata` and `abilities.vdata`.
//!
//! Hero and equipped-item inputs used to reconstruct passive bullet and spirit resistance.
//!
//! Last updated: 2026-08-06

/// Hero-defined resistance and spirit-power progression, in percentage points.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct HeroResistanceStats {
    pub base_bullet_resist: f32,
    pub base_spirit_resist: f32,
    pub base_spirit_power: f32,
    pub bullet_resist_per_level: f32,
    pub spirit_resist_per_level: f32,
    pub spirit_power_per_level: f32,
    pub bullet_resist_per_spirit_power: f32,
    pub spirit_resist_per_spirit_power: f32,
}

/// Return the resistance inputs for a hero.
pub fn hero_resistance_stats(hero_id: i64) -> HeroResistanceStats {
    match hero_id {
        8 => HeroResistanceStats {
            spirit_resist_per_level: 0.625,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        11 => HeroResistanceStats {
            bullet_resist_per_level: 0.625,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        12 => HeroResistanceStats {
            spirit_resist_per_level: 0.625,
            spirit_power_per_level: 1.3,
            ..HeroResistanceStats::default()
        },
        15 => HeroResistanceStats {
            bullet_resist_per_level: 0.3,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        31 => HeroResistanceStats {
            base_spirit_resist: 10.0,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        50 => HeroResistanceStats {
            base_spirit_resist: -15.0,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        61 => HeroResistanceStats {
            base_spirit_resist: -15.0,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        65 => HeroResistanceStats {
            spirit_power_per_level: 1.1,
            bullet_resist_per_spirit_power: 0.12178,
            spirit_resist_per_spirit_power: 0.12178,
            ..HeroResistanceStats::default()
        },
        70 => HeroResistanceStats {
            base_spirit_resist: 10.0,
            spirit_power_per_level: 1.1,
            ..HeroResistanceStats::default()
        },
        _ => HeroResistanceStats::default(),
    }
}

/// Unconditional resistance supplied by an equipped item.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ItemResistanceStats {
    pub bullet_resist: f32,
    pub spirit_resist: f32,
}

/// Return the unconditional resistance supplied by an item.
pub fn item_resistance_stats(ability_id: u32) -> ItemResistanceStats {
    match ability_id {
        26002154 => ItemResistanceStats {
            bullet_resist: 6.0,
            ..ItemResistanceStats::default()
        },
        223594321 => ItemResistanceStats {
            spirit_resist: 15.0,
            ..ItemResistanceStats::default()
        },
        630839635 => ItemResistanceStats {
            bullet_resist: 5.0,
            spirit_resist: 5.0,
        },
        677738769 => ItemResistanceStats {
            bullet_resist: 15.0,
            spirit_resist: 14.0,
        },
        800008313 => ItemResistanceStats {
            bullet_resist: 12.0,
            ..ItemResistanceStats::default()
        },
        951866250 => ItemResistanceStats {
            bullet_resist: 10.0,
            spirit_resist: 10.0,
        },
        989206714 => ItemResistanceStats {
            spirit_resist: 8.0,
            ..ItemResistanceStats::default()
        },
        1055679805 => ItemResistanceStats {
            bullet_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        1113837674 => ItemResistanceStats {
            spirit_resist: 12.0,
            ..ItemResistanceStats::default()
        },
        1193964439 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        1200177229 => ItemResistanceStats {
            spirit_resist: 15.0,
            ..ItemResistanceStats::default()
        },
        1235347618 => ItemResistanceStats {
            bullet_resist: 18.0,
            ..ItemResistanceStats::default()
        },
        1282141666 => ItemResistanceStats {
            bullet_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        1378931225 => ItemResistanceStats {
            bullet_resist: 12.0,
            ..ItemResistanceStats::default()
        },
        1409190604 => ItemResistanceStats {
            spirit_resist: 40.0,
            ..ItemResistanceStats::default()
        },
        1414319208 => ItemResistanceStats {
            bullet_resist: 8.0,
            ..ItemResistanceStats::default()
        },
        1427630806 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        1797283378 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        1925087134 => ItemResistanceStats {
            bullet_resist: 8.0,
            ..ItemResistanceStats::default()
        },
        1955841979 => ItemResistanceStats {
            spirit_resist: 18.0,
            ..ItemResistanceStats::default()
        },
        1976391348 => ItemResistanceStats {
            spirit_resist: 6.0,
            ..ItemResistanceStats::default()
        },
        2059712766 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        2081037738 => ItemResistanceStats {
            spirit_resist: 8.0,
            ..ItemResistanceStats::default()
        },
        2108215830 => ItemResistanceStats {
            bullet_resist: 17.0,
            ..ItemResistanceStats::default()
        },
        2163598980 => ItemResistanceStats {
            spirit_resist: 30.0,
            ..ItemResistanceStats::default()
        },
        2717651715 => ItemResistanceStats {
            bullet_resist: 8.0,
            ..ItemResistanceStats::default()
        },
        2971868509 => ItemResistanceStats {
            bullet_resist: 9.0,
            ..ItemResistanceStats::default()
        },
        3005970438 => ItemResistanceStats {
            spirit_resist: 17.0,
            ..ItemResistanceStats::default()
        },
        3028234315 => ItemResistanceStats {
            spirit_resist: 22.0,
            ..ItemResistanceStats::default()
        },
        3140772621 => ItemResistanceStats {
            bullet_resist: 30.0,
            ..ItemResistanceStats::default()
        },
        3361075077 => ItemResistanceStats {
            bullet_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        3361811174 => ItemResistanceStats {
            bullet_resist: 15.0,
            ..ItemResistanceStats::default()
        },
        3403085434 => ItemResistanceStats {
            bullet_resist: 6.0,
            ..ItemResistanceStats::default()
        },
        3713423303 => ItemResistanceStats {
            bullet_resist: 18.0,
            ..ItemResistanceStats::default()
        },
        3731635960 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        3812615317 => ItemResistanceStats {
            spirit_resist: 10.0,
            ..ItemResistanceStats::default()
        },
        3970837787 => ItemResistanceStats {
            spirit_resist: 18.0,
            ..ItemResistanceStats::default()
        },
        4238249888 => ItemResistanceStats {
            bullet_resist: 40.0,
            spirit_resist: 40.0,
        },
        _ => ItemResistanceStats::default(),
    }
}
