//! Run: cargo run --manifest-path scripts/compute-abilities-hash-table/Cargo.toml
//!
//! Generates crates/boon/src/abilities.rs from abilities.vdata.
//!
//! abilities.vdata comes from Deadlock's VPK game data, extracted using
//! Source2Viewer (ValveResourceFormat). It uses Valve's KV3 format — a
//! non-standard JSON-like structure where top-level keys (indented one tab)
//! are ability/item identifiers.
//!
//! The ability_id field in k_EUserMsg_ItemPurchaseNotification (msg_type 360)
//! is a CUtlStringToken, which Source 2 computes as MurmurHash2 with seed
//! 0x31415926. We verified this by matching all sample purchase IDs from
//! a demo file against hashed vdata keys.

use std::fs;
use std::io::Write;
use std::path::Path;

const SEED: u32 = 0x31415926;

/// MurmurHash2 (32-bit) matching Source 2's CUtlStringToken implementation.
fn murmur_hash2(key: &[u8]) -> u32 {
    const M: u32 = 0x5BD1E995;
    const R: i32 = 24;

    let len = key.len();
    let mut h: u32 = SEED ^ (len as u32);
    let mut i = 0;

    while i + 4 <= len {
        let mut k = u32::from_le_bytes([key[i], key[i + 1], key[i + 2], key[i + 3]]);
        k = k.wrapping_mul(M);
        k ^= k >> R;
        k = k.wrapping_mul(M);
        h = h.wrapping_mul(M);
        h ^= k;
        i += 4;
    }

    let remaining = len - i;
    if remaining >= 3 {
        h ^= (key[i + 2] as u32) << 16;
    }
    if remaining >= 2 {
        h ^= (key[i + 1] as u32) << 8;
    }
    if remaining >= 1 {
        h ^= key[i] as u32;
        h = h.wrapping_mul(M);
    }

    h ^= h >> 13;
    h = h.wrapping_mul(M);
    h ^= h >> 15;
    h
}

/// Extract top-level ability/item name keys from abilities.vdata.
///
/// Matches lines like `\tability_name = ` — one tab of indent followed by
/// a word-character key. Skips metadata keys (`generic_data_type`, `_include`).
fn extract_ability_names(content: &str) -> Vec<&str> {
    let skip = ["generic_data_type", "_include"];
    let mut names = Vec::new();

    for line in content.lines() {
        // Must start with exactly one tab, then a word char (not another tab)
        let Some(rest) = line.strip_prefix('\t') else {
            continue;
        };
        if rest.starts_with('\t') {
            continue;
        }

        // Find the key: contiguous word characters before whitespace/`=`
        let key_end = rest
            .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .unwrap_or(rest.len());
        if key_end == 0 {
            continue;
        }
        let key = &rest[..key_end];

        // Check that what follows is ` = ` (with optional whitespace)
        let after = rest[key_end..].trim_start();
        if !after.starts_with('=') {
            continue;
        }

        if skip.contains(&key) {
            continue;
        }

        names.push(key);
    }

    names
}

fn main() {
    let vdata_path = Path::new("abilities.vdata");
    let output_path = Path::new("crates/boon/src/abilities.rs");

    if !vdata_path.exists() {
        eprintln!("abilities.vdata not found at {}", vdata_path.display());
        eprintln!("Run this from the repo root.");
        std::process::exit(1);
    }

    let content = fs::read_to_string(vdata_path).expect("failed to read abilities.vdata");

    let names = extract_ability_names(&content);
    eprintln!(
        "Extracted {} ability names from {}",
        names.len(),
        vdata_path.display()
    );

    // Compute hashes and sort by hash for deterministic output
    let mut entries: Vec<(u32, &str)> = names
        .iter()
        .map(|&name| (murmur_hash2(name.as_bytes()), name))
        .collect();
    entries.sort_by_key(|&(h, _)| h);

    // Write the Rust source file
    let mut out = fs::File::create(output_path).expect("failed to create output file");

    writeln!(
        out,
        "/// Auto-generated by scripts/compute-abilities-hash-table from abilities.vdata"
    )
    .unwrap();
    writeln!(
        out,
        "/// Maps MurmurHash2(ability_name, seed=0x31415926) → ability name string."
    )
    .unwrap();
    writeln!(out, "pub fn ability_name(id: u32) -> &'static str {{").unwrap();
    writeln!(out, "    match id {{").unwrap();

    for (hash, name) in &entries {
        writeln!(out, "        {hash} => \"{name}\",").unwrap();
    }

    writeln!(out, "        _ => \"ABILITY_NOT_FOUND\",").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    eprintln!(
        "Wrote {} with {} entries",
        output_path.display(),
        entries.len()
    );
}
